# This is a basic workflow to help you get started with Actions

name: Test workflow

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    name: Run pipeline with test data
    # Only run on push if this is the nf-core dev branch (merged PRs)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        NXF_VER:
          - "21.10.6"
        # MUST use earlier versionaffected by this issue: https://github.com/nextflow-io/nextflow/issues/3023  - "latest-everything"
        RUN_PARAMS:
          - "--gldsAccession GLDS-48  --ensemblVersion 96 --ref_source ensembl --truncateTo 100 --annotation_path https://figshare.com/ndownloader/files/35939642"
          - "--gldsAccession GLDS-194 --ensemblVersion 96 --ref_source ensembl --truncateTo 100 --annotation_path https://figshare.com/ndownloader/files/35939642"
          - "--gldsAccession GLDS-251 --ensemblVersion 44 --ref_source ensembl_plants --truncateTo 100 --annotation_path https://figshare.com/ndownloader/files/35939648"
    environment: Nextflow_Tower
    env:
       TOWER_ACCESS_TOKEN: ${{ secrets.TOWER_ACCESS_TOKEN }}
       TOWER_WORKSPACE_ID: ${{ secrets.TOWER_WORKSPACE_ID }}
    steps:
      - name: Check out pipeline code
        uses: actions/checkout@v2

      - name: Install Nextflow
        uses: nf-core/setup-nextflow@v1.1.0
        with:
          version: "${{ matrix.NXF_VER }}"

      - name: Run pipeline with test data
        run: |
          nextflow run ${GITHUB_WORKSPACE}  ${{ matrix.RUN_PARAMS }} -with-tower -name "GH_CI_$(date '+%s')"
